name: bun-build

concurrency:
  group: bun-build-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on: [push]
  # push:
  #   branches:
  #     - main
  #     - ci/*
  #   paths:
  #     # Build files
  #     # Source files
  #     - "src/**/*"
  #     - "packages/{bun-usockets,bun-uws}/src/**/*"
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     # Build files
  #     - "a"
  #     # Source files
  #     - "src/**/*"
  #     - "packages/{bun-usockets,bun-uws}/src/**/*"
  # workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.id }})
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: linux-x64
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ matrix.id }}
          path: build
      - name: Setup APT
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          version: "1" # increment when packages change
          packages: |
            make
            cmake
            ccache
            ninja-build
            lsb-release
            software-properties-common
            gnupg
            gnupg1
            gnupg2
            file
            libc-dev
            libxml2
            libxml2-dev
            rsync
            unzip
            xz-utils
            tar
            gzip
            perl
            python3
            ruby
      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build
        run: |
          bun install -g esbuild
          bun run build
          ls
          ls build
